### ISSUE TITLE
How is the wiring done?

### ISSUE THREAD

**Issue by Rob0xFF** [Markus-Be/Microscope-ESP32#1]
The PWR line is normally open/GND and pulled high when the button is switched. Nevertheless, the KEY line is pulled high normally by the MCU of the scope, so how can the DAC OUT manipulate this line?

**Comment by Markus-Be** [comment]
Hello,

I apologize for the late answer.
Since the project has been a long time ago, I've just recreated it again.

I use the following ESP32 board:
http://mh.nodebb.com/topic/2/mh-et-live-esp32-devkit

**Wiring:**
Microscope - ESP32
GND - GND
PWR - DAC_1
MENU - DAC_2

It still worked but I did not inspect the Microscope furhter.
